version: '3.1'

services:
  postgres:
    container_name: docker_postgres
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: jarvis_db_manager
      POSTGRES_USER: jarvis_db_manager
      POSTGRES_PASSWORD: jarvis_db_manager
    volumes:
      - ./postgres-create-schemas.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - custom

networks:
  custom:
    driver: bridge